name: 'Tencent CloudBase Github Action'
description: '云开发 Github Action 可以支持将你的项目一键部署到云开发环境'
author: bookerzhao
branding:
  icon: upload-cloud
  color: blue
inputs:
  secretId:
    description: '云开发 secretId'
    required: true
  secretKey:
    description: '云开发 secretKey'
    required: true
  envId:
    description: '云开发环境 Id'
    required: true
  localPath:
    description: '项目静态文件路径'
    required: true
  cloudPath:
    description: '服务器部署路径'
    required: true

runs:
  using: 'composite'
  steps:
    - run: bash ${{ github.action_path }}/script/run.sh ${{ inputs.secretId }} ${{ inputs.secretKey }} ${{ inputs.envId }} ${{ inputs.localPath }} ${{ inputs.cloudPath }}
      shell: bash